[package]
name = "clike"
version = "0.1.0"
authors = ["Parker TenBroeck"]
build = "build.rs" # LALRPOP preprocessing

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies] # <-- We added this and everything after!
lalrpop = "0.19.7"

[dependencies]
lalrpop-util = "0.19.7"
unicode-xid = "0.2.2"
regex = "1"