[package]
name = "clike"
version = "0.1.0"
authors = ["Parker TenBroeck"]
build = "build.rs"
edition = "2021"


[build-dependencies]
lalrpop = "0.19.7"


[dependencies]
lalrpop-util = "0.19.8"
util = { path = "../util" }
unicode-xid = "0.2.2"
regex = "1"
