[package]
name = "mips_emulator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["external_handlers"]
external_handlers = []
system_call_plugins = ["external_handlers"]

[dependencies]
