name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-web:
    name: Build Web
    runs-on: ubuntu-latest

    steps:
    - name: Install latest nightly
#    - uses: actions/checkout@v2
    - uses: jetli/wasm-pack-action@v0.3.0

#    - name: Build
#      run: cargo build --release --verbose
#    - name: Run tests
#      run: cargo test --verbose
    - name: Build/Test Web
      run: ./clike-gui/build_web.sh
    - name: Finish
      run: ./clike-gui/setup_web.sh
      
      
      
    - name: Upload production-ready build files
      uses: actions/upload-artifact@v2
      with:
        name: production-files
        path: ./clike-gui/docs
  
  deploy:
    name: Deploy
    needs: build-web
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: production-files
        path: ./clike-gui/docs
    
    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./clike-gui/docs
