name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-web:
    name: Build Web
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: wasm32-unknown-unknown
#          components: wasm-bindgen-cli
      - uses: jetli/wasm-pack-action@v0.3.0
      - uses: jetli/wasm-bindgen-action@v0.1.0
          with:
            # Optional version of wasm-bindgen to install(eg. '0.2.68', 'latest')
            version: 'latest'
      
    
      - name: Install 
        run: sudo apt-get install -y binaryen
#      - name: Install
#        run: cargo install wasm-bindgen-cli
#      - name: Build/Test Web
#        run: cd clike-gui chmod +x filename.sh
      - name: Build/Test Web
        working-directory: ./clike_gui
        run: chmod +x build_web.sh
      - name: Build/Test Web
        working-directory: ./clike_gui
        run: ./build_web.sh
#      - name: Finish
#        run: ./setup_web.sh
      
      - name: Upload production-ready build files
        uses: actions/upload-artifact@v2
        with:
          name: production-files
          path: ./clike_gui/docs
  
  deploy:
    name: Deploy
    needs: build-web
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: production-files
        path: ./clike_gui/docs
    
    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./clike_gui/docs