name: Rust

on:
  push:
    branches: [ release ]
#  pull_request:
#    branches: [ release ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-web:
    name: Build Web
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: wasm32-unknown-unknown
      - uses: jetli/wasm-pack-action@v0.3.0
      - uses: jetli/wasm-bindgen-action@v0.1.0
      
    
      - name: Install 
        run: sudo apt-get install -y binaryen
      - name: Build/Test Web
        working-directory: ./app
        run: |
         chmod +x build_web.sh
         ./build_web.sh
      
      - name: Upload production-ready build files
        uses: actions/upload-artifact@v2
        with:
          name: production-files
          path: ./app/docs
  
  deploy:
    name: Deploy
    needs: build-web
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/release'
    
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: production-files
        path: ./app/docs
    
    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./app/docs