name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-web:
    name: Build Web
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: wasm32-unknown-unknown
#          components: wasm-bindgen-cli
      - uses: jetli/wasm-pack-action@v0.3.0
      
    
      - name: Install 
        run: sudo apt-get install -y binaryen
      - name: Install
        run: cargo install wasm-bindgen-cli
      - name: Build/Test Web
        run: cd clike-gui
      - name: Build/Test Web
        run: ./build_web.sh
      - name: Finish
        run: ./setup_web.sh
      
      - name: Upload production-ready build files
        uses: actions/upload-artifact@v2
        with:
          name: production-files
          path: ./clike-gui/docs
  
  deploy:
    name: Deploy
    needs: build-web
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: production-files
        path: ./clike-gui/docs
    
    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./clike-gui/docs
